<?php

namespace AppBundle\Repository;

/**
 * AxeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AxeRepository extends \Doctrine\ORM\EntityRepository
{
}
