<?php

namespace AppBundle\Repository;

/**
 * DifficulteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DifficulteRepository extends \Doctrine\ORM\EntityRepository
{
}
