<?php

namespace AppBundle\Repository;

/**
 * ParrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParrainRepository extends \Doctrine\ORM\EntityRepository
{
}
